### ISSUE TITLE
Uncaught Error: Unexpected module 'FlashMessagesModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.

### ISSUE THREAD

**Issue by GerritsTom** [moff/angular2-flash-messages#24]
Uncaught Error: Unexpected module 'FlashMessagesModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:50893:34)
    at http://localhost:4200/vendor.bundle.js:64625:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:64607:54)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:75884:70)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:75857:36)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:75786:37)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5513:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5499:21)
    at Object.181 (http://localhost:4200/main.bundle.js:372:124)

**Comment by Jayawardhana** [comment]
I have same error
[WDS] Disconnected!
vendor.bundle.js:67956:10
Error: Unexpected module 'FlashMessageModule' declared by the module 'AppModule'
